spring:
  application:
    name: gateway

  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/academy
        registration:
          gateway:
            provider: keycloak-provider
            client-id: ${client_id}
            client-secret: ${client_secret}
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8081/login/oauth2/code/keycloak'

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-students
          uri: lb://ms-students
          predicates:
            - Path=/students/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:8761/eureka
info:
  app: gateway
  name: gateway
  description: Gateway to ms access
  version: 1.0.0

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081